(define (make-monitored fun)
  (let ((count 0))
    (lambda (x)
      (cond ((eq? x 'how-many-calls?) count)
            ((eq? x 'reset-count) (set! count 0) count)
            (else (set! count (+ count 1)) (fun x))))))
(define s (make-monitored sqrt))
(s 100)
(s 'how-many-calls?)
(s 'how-many-calls?)
(s 10000)
(s 'how-many-calls?)
(s 'reset-count)
(s 'how-many-calls?)
(s 9)
(s 'how-many-calls?)
(s 'reset-count)
(s 81)
(s 'how-many-calls?)
